const express =require('express')
const app = express();
const axios = require('axios')
/* app.get('/',(req,res)=>{
    res.send('请求成功!')
}) */
app.get('/api/proxy',(req,res)=>{
    let menu = encodeURI('沙拉')//"%E6%B2%99%E6%8B%89" 转换编码
    // axios.get(`https://apis.juhe.cn/cook/query.php?menu=${menu}&key=fd075da6f7c344cbbb8948ce659312ff&dtype=json`)
    // .then(result=>{
    //     res.send({msg:result.data})
    // })
    axios.post(`http://rap2api.taobao.org/app/mock/287809/auth/getUserTreeInfo`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
app.post('/api/proxy/h',(req,res)=>{
    let menu = encodeURI('沙拉')//"%E6%B2%99%E6%8B%89" 转换编码
    // axios.get(`https://apis.juhe.cn/cook/query.php?menu=${menu}&key=fd075da6f7c344cbbb8948ce659312ff&dtype=json`)
    // .then(result=>{
    //     res.send({msg:result.data})
    // })
    axios.post(`http://rap2api.taobao.org/app/mock/287809/auth/getUserTreeInfo`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//注册中间件
const bodyParser = require('body-parser');
app.use(bodyParser.urlencoded({extended:false}))
// No 'Access-Control-Allow-Origin' header is present on the requested resource.
app.all('*', function (req, res, next) {
    res.header('Access-Control-Allow-Origin', '*')
    next()
})
// //挂载静态资源
// app.use(express.static('./index'))
// // 把 node_modules 文件夹，托管为静态资源目录
// app.use('/node_modules', express.static('./node_modules'))
const port = 8080;
const ip = '127.0.0.1'
app.listen(port,`${ip}`,()=>{
    console.log(`Express server runing at http://${ip}:${port}`)
})

//登录接口
app.post('/auth/login',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/auth/login`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//获取信息接口
app.post('/auth/getUserTreeInfo',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/auth/getUserTreeInfo`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//退出登录
app.post('/auth/logout',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/auth/logout`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单查询
app.post('/order-catering-server-api/api/order/getOrderList',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//车餐/站餐接单
app.post('/order-catering-server-api/api/order/receivingOrder',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/receivingOrder`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//配送中
app.post('/order-catering-server-api/api/order/shipping',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/shipping`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//已完成
app.post('/order-catering-server-api/api/order/finishOrder',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/finishOrder`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//站餐核销页面已取餐接口
app.post('/order-catering-server-api/api/order/takeFoods',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/takeFoods`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//备货
app.post('/order-catering-server-api/api/order/preparingGoods',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/preparingGoods`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//核销获取订单详情
app.post('/api/order/getOrderDetailByTakeCode',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/api/order/getOrderDetailByTakeCode`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单确认
app.post('/order-catering-server-api/api/order/confirmOfOrder',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/confirmOfOrder`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单状态和异常单原因
app.post('/api/basedic/getReasonList',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/basedic/getReasonList`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//退单原因
app.post('/api/basedic/getChargebackReasonList',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/basedic/getReasonList`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//商家通讯录
app.post('/api/company/getMailList',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/basedic/getReasonList`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//标记处理
app.post('/order-catering-server-api/api/orderException/insertOrderException',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/orderException/insertOrderException`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//异常处理
app.post('/order-catering-server-api/api/orderException/updateOrderException',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/orderException/updateOrderException`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//查询订单轨迹
app.post('/api/log/getOrderPath',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/api/log/getOrderPath`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//轮询新订单查询
app.post('/order-catering-server-api/api/order/getNewOrderInfo',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getNewOrderInfo`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单数量查询 (轮询)
app.post('/order-catering-server-api/api/order/getOrderCountInfo',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderCountInfo`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//搜索框搜索
app.post('/order-catering-server-api/api/order/getOrderInfo',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderInfo`)
    .then(result=>{
        res.send({msg:result.data})
    })
})

//退单、拒单
app.post('/order-catering-server-api/api/order/refundOrder',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/refundOrder`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//车站收餐--统计列表
app.post('/api/distribution/stationCollectCount',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/api/distribution/stationCollectCount`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//车站收餐--车上配餐
app.post('/api/distribution/trainSendCount',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/api/distribution/trainSendCount`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//车次开售
app.post('/api/distribution/checkTrainOpen',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/api/distribution/checkTrainOpen`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//车次担当
app.post('/api/distribution/checkTrain',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/api/distribution/checkTrain`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//获取可选车次接口
app.post('/api/trains/selectTrains',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/api/trains/selectTrains`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//铃声提醒设置接口
app.post('/order-catering-server-api/api/company/ringSetting',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/company/ringSetting`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//预订单设置接口
app.post('/order-catering-server-api/api/sljyMerchantAppendix/bookingSetting',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/sljyMerchantAppendix/bookingSetting`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单车-待处理-新单
app.post('/order-catering-server-api/api/order/getOrderList_113',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_113`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单车-待处理-当日
app.post('/order-catering-server-api/api/order/getOrderList_114',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_114`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单车-待处理-已备货
app.post('/order-catering-server-api/api/order/getOrderList_115',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_115`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单车-待处理-配送中
app.post('/order-catering-server-api/api/order/getOrderList_116',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_116`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单车-预定
app.post('/order-catering-server-api/api/order/getOrderList_12',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_12`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单车-异常
app.post('/order-catering-server-api/api/order/getOrderList_13',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_13`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单车-历史-全部
app.post('/order-catering-server-api/order-catering-server-api/api/order/getOrderList_100',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_100`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单-自营
app.post('/order-catering-server-api/api/order/getOrderList_27',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_27`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单-站配
app.post('/order-catering-server-api/api/order/getOrderList_356',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_356`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//订单车-车配
app.post('/order-catering-server-api/api/order/getOrderList_47',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/order-catering-server-api/api/order/getOrderList_47`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
//获取管理员用户信息接口
app.post('/auth/getAdminInfo',(req,res)=>{
    axios.post(`http://rap2api.taobao.org/app/mock/287809/auth/getAdminInfo`)
    .then(result=>{
        res.send({msg:result.data})
    })
})
